export const SET_MINIFIGS = 'SET_MINIFIGS';
export const SET_MINIFIGS_FAILED = 'SET_MINIFIGS_FAILED';
export const SET_TOTAL_NUMBER = 'SET_TOTAL_NUMBER';
export const SET_TOTAL_OWNED = 'SET_TOTAL_OWNED';
